/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package badgeripper;

import java.awt.HeadlessException;
import java.io.BufferedOutputStream;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.UnsupportedEncodingException;
import java.net.URL;
import java.net.URLDecoder;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JList;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrador
 */
public class BadgeRipper extends javax.swing.JFrame {

    static String external_flash_texts;
    static BufferedReader bf1;
    static ArrayList<String> list_Badges = new ArrayList<String>();
    static JList list;
    static int num = 0;

    /**
     * Creates new form BadgeRipper
     */
    public BadgeRipper() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jTextField1 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BadgeRipper by jomp16");

        jButton1.setText("Baixar todos os emblemas");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("Baixar e visualizar emblema");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jList1);

        jTextField1.setText("http://habbixed.alwaysdata.net/external_flash_texts.txt");

        jButton4.setText("Carregar lista de emblemas!");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)))
            .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-581)/2, (screenSize.height-512)/2, 581, 512);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String lineBuffer;
        try {
            String path = BadgeRipper.class.getProtectionDomain().getCodeSource().getLocation().getPath();
            String name = URLDecoder.decode(path, "UTF-8");
            name = name.substring(0, name.indexOf(".jar"));
            name = name.substring(name.lastIndexOf(':') - 1, name.lastIndexOf('/') + 1).replace('%', ' ');
            downloadFile(jTextField1.getText(), name + "/DOWNLOADS/", "external_flash_texts.txt", false);
            bf1 = new BufferedReader(new FileReader((name + "/DOWNLOADS/external_flash_texts.txt")));
            while ((lineBuffer = bf1.readLine()) != null) {
                if (lineBuffer.contains("badge_name_")) {
                    int index = lineBuffer.indexOf("badge_name_");
                    int num3 = lineBuffer.indexOf("=");
                    if (!lineBuffer.contains("badge_name_fb")) {
                        String item = lineBuffer.substring(index + 11, (num3 - index));
                        if (item != null) {
                            list_Badges.add(item);
                        }
                    }
                }
            }
            list = new JList(list_Badges.toArray());

            jList1.setModel(list.getModel());
        } catch (IOException | HeadlessException e) {
            //System.out.println(e);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            String path = BadgeRipper.class.getProtectionDomain().getCodeSource().getLocation().getPath();
            String name = URLDecoder.decode(path, "UTF-8");
            name = name.substring(0, name.indexOf(".jar"));
            name = name.substring(name.lastIndexOf(':') - 1, name.lastIndexOf('/') + 1).replace('%', ' ');
            downloadFile("http://habbo.hs.llnwd.net/c_images/album1584/" + jList1.getSelectedValue().toString() + ".gif", name + "/DOWNLOADS/", jList1.getSelectedValue().toString() + ".gif", true);
            ImageIcon icon = new ImageIcon("DOWNLOADS/" + jList1.getSelectedValue().toString() + ".gif");
            jLabel1.setIcon(icon);
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Thread t1 = new downloadBadges();
        //jProgressBar1.setIndeterminate(true); //.setMaximum(list_Badges.size());
        t1.start();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BadgeRipper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new BadgeRipper().setVisible(true);
                //jProgressBar1.setIndeterminate(true);
            }
        });
        try {
            String path = BadgeRipper.class.getProtectionDomain().getCodeSource().getLocation().getPath();
            String name = URLDecoder.decode(path, "UTF-8");
            name = name.substring(0, name.indexOf(".jar"));
            name = name.substring(name.lastIndexOf(':') - 1, name.lastIndexOf('/') + 1).replace('%', ' ');

            //JOptionPane.showMessageDialog(null, decodedPath);
            File pasta1 = new File(name + "/DOWNLOADS");
            if (pasta1.exists()) {
            } else {
                pasta1.mkdirs();
            }
        } catch (UnsupportedEncodingException | HeadlessException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private static javax.swing.JList jList1;
    private static javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    public static void downloadFile(String urla, String diretorio, String file, boolean showerror) {
        File f = new File(diretorio + file);
        if (!f.exists()) {
            try {
                URL url1 = new URL(urla);
                OutputStream out;
                try (InputStream in = url1.openStream()) {
                    out = new BufferedOutputStream(new FileOutputStream(new File(diretorio + file)));
                    byte[] buf = new byte[2048];
                    int n;
                    while ((n = in.read(buf)) != -1) {
                        out.write(buf, 0, n);
                    }
                }
                out.close();
            } catch (Exception e) {
                if (showerror) {
                    JOptionPane.showMessageDialog(null, "Não foi possível baixar esse emblema!");
                }
            }
        } else {
        }
    }

    static class downloadBadges extends Thread {

        @Override
        public void run() {
            try {
                String path = BadgeRipper.class.getProtectionDomain().getCodeSource().getLocation().getPath();
                String name = URLDecoder.decode(path, "UTF-8");
                name = name.substring(0, name.indexOf(".jar"));
                name = name.substring(name.lastIndexOf(':') - 1, name.lastIndexOf('/') + 1).replace('%', ' ');
                jProgressBar1.setMinimum(1);
                jProgressBar1.setMaximum(list_Badges.size());
                for (int i = 0; i < list_Badges.size(); i++) {
                    downloadFile("http://habbo.hs.llnwd.net/c_images/album1584/" + list_Badges.get(i) + ".gif", name + "/DOWNLOADS/", list_Badges.get(i) + ".gif", false);
                    jProgressBar1.setValue(i);
                }
                JOptionPane.showMessageDialog(null, "Downloads de todos os emblemas concluido com sucesso!");
            } catch (UnsupportedEncodingException | HeadlessException e) {
            }
        }
    }
}
